### ISSUE TITLE
MqttSubmodelAPIObserver.elementUpdated does not publish newValue

### ISSUE THREAD

**Issue by webs397** [eclipse-basyx/basyx-java-components#118]
Hi there,

I am trying to communicate between containers using MQTT. The Eventing works well, but the new value of the updated submodel element would be useful information to publish as well. It is possible to retrieve the missing information via an API request by watching the subscribed topic for the submodel element and then sending the API request, but this increases traffic unnecessarily. 

Would it be possible to extend the "elementUpdated" function to include the "newValue" parameter that is passed to the function but doesn't seem to be used?

```Java	
public void elementUpdated(String idShortPath, Object newValue) {
	if (filter(idShortPath)) {
		sendMqttMessage(MqttSubmodelAPIHelper.TOPIC_UPDATEELEMENT, getCombinedMessage(aasIdentifier.getId(), submodelIdentifier.getId(), idShortPath));
		}
	}
```

Please let me know if I am missing something here.

**Comment by FrankSchnicke** [comment]
Hi,

since the value of a SubmodelElement can be quite large (e.g., a SubmodelElementCollection receiving a nested SubmodelElement structure), we implemented the MQTT eventing without sending out the new value. 
This issue can be alleviated by explicit blacklisting/whitelisting or similar features - however, this is not on our roadmap right now. Nevertheless, if you raise a PR providing this, I will gladly integrate it in the next release.


Best regards,
Frank
