### ISSUE TITLE
How to start an AAS server in development-v2

### ISSUE THREAD

**Issue by OParczyk** [eclipse-basyx/basyx-java-components#25]
I've tried to start a AAS server on the development-v2 branch, as I need to aim for as much AAS Spec. v3 support as possible.
Porting an v1 application hasn't proofed to difficult, however I can't seem to find out how I'm supposed to start the AAS Server component. Registry still exists.

The corresponding files were deleted in #6 and since as far as I can tell no substitute has been added.
How do I start an AAS server on the develpoment-v2 branch?

**Comment by FrankSchnicke** [comment]
The development-v2 branch is only providing the content for the registry in a preview stage since we're planning to restructure the SDK and Components in the process of preparing the v2 release. 

Thus, right now there no AAS Server provided for v2. However, feel free to use the AAS Server of v1 with the Registry of v2. Please note that this may not work out of the box.

I will update this ticket as soon as the AAS Server is available in v2.

**Comment by FrankSchnicke** [comment]
We have started the work on the AAS Repository and Submodel Repository in the following branch:

https://github.com/eclipse-basyx/basyx-java-components/tree/development-v2
