### ISSUE TITLE
[Suggestion] Use Spring Boot as Basis Framework

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-basyx/basyx-java-components#395]
Hi,

I am currently setting up several different AAS servers and registries in the Fed-X-Pro project. In the process, I have noticed again and again how complicated it is to create and also understand the configurations for the two services. Furthermore, the configurations are also built differently (key-value map, properties file). I also noticed when looking through the source code that many techniques are implemented by myself.

For this reason I would like to suggest to write both services with Spring Boot. The following advantages result from this:
* Main developer is VMware
* Defined lifecycle of Spring packages
* Many functions can be implemented fast and easy with Dependency Injection and in MVC
* Extensively configurable and many functions out of the box (web service incl. security configuration, mail service, database connection)
* and even more

I also think this is a good foundation to build a good maintenance for the source code. Also state of the art monitoring solutions can be applied to monitor the services.

Hope that helps.

KR,
BlackRose01

**Comment by FrankSchnicke** [comment]
Hi BlackRose01,

thank you very much for pointing out your findings with the configuration of BaSyx and suggesting Spring. We're currently in the development of BaSyx V2, supporting AAS Metamodel and API in Version 3:
https://github.com/eclipse-basyx/basyx-java-server-sdk

For this, we're leveraging Spring Boot to its full extend. Depending on your use case, I would suggest migrating to BaSyx V2 as soon as possible. The components are already available on DockerHub (cf. the documentation in the aforementioned repository).

For BaSyx V1, we're not planning on migrating to Spring anymore due to the older nature of the metamodel and API.
